### ISSUE TITLE
Berlin for output files

### ISSUE THREAD

**Issue by okazymyrov** [aircrack-ng/aircrack-ng-archive#124]
It seems like "--berlin 2" affects only console output. The CSV file generated by 
`/usr/local/sbin/airodump-ng --ignore-negative-one  --beacons --showack --uptime --wps --berlin 2 --band abg --write test --output-format csv --output-format kismet --write-interval 1 wlan1`
grows over time.

**Comment by aircrack-ng** [comment]
It is a display option, so it's normal.
