### ISSUE TITLE
wpa2 cracking from multiple PCs

### ISSUE THREAD

**Issue by BlaacckK** [aircrack-ng/aircrack-ng-archive#133]
Hello all,
I want to lnow that how can i crack wpa2 from multiple computers
i think that the wordlist should be divided by the number of computer to crack the password faster.
How can i do it?

**Comment by aircrack-ng** [comment]
This is a bug tracker, ask it in the forum and you'll get the answer.

**Comment by Mister-X-** [comment]
By the way, check out the script directory, there is one script called dcrack.py (check out the blog, it is mentioned in a fairly recent post AFAIK).
