### ISSUE TITLE
Is it compatible with the NetGear A6200 WiFi adapter?

### ISSUE THREAD

**Issue by natiya** [aircrack-ng/aircrack-ng-archive#142]
I'm using airodump-ng on Windows 10 and I've got the NetGear A6200 WiFi adapter which supports monitor mode and it's able to capture 802.11 packets. However, when I run the command 

**airodump-ng --bssid XX:XX:XX:XX:XX:XX "Wi-Fi 2"**

it says that

**Adapter <Wi-Fi 2> not supported**

am I doing something wrong? Do I need any additional packets?

**Comment by aircrack-ng** [comment]
@natiya, such question belong to the forum after doing proper research.

Airodump-ng only works with Airpcap adapters on Windows.

**Comment by natiya** [comment]
but AirPcap doesn't work on Windows 10, does it?
