### ISSUE TITLE
airbase-ng not working

### ISSUE THREAD

**Issue by toshi382** [aircrack-ng/aircrack-ng-archive#156]
Hello guys,

I'm using fedora 27 and successfully installed aircrack-ng.

airodump-ng is properly working, however when I tried using airbase-ng using the command below.

# airbase-ng -a 4C:81:20:96:6B:12 -essid "egi" -c 5 wlp2s0mon

the result is 

"airbase-ng --help" for help.

Did I commit mistake?

**Comment by aircrack-ng** [comment]
This is not a bug, this is an error in your parameters, it's --essid. Please use the forum next time unless you are 100% sure it is a bug.

**Comment by toshi382** [comment]
Ok thanks... removing the —essid solves the problem...
