### ISSUE TITLE
Not Compiling (Compile Error)

### ISSUE THREAD

**Issue by dseif0x** [aircrack-ng/aircrack-ng-archive#166]
I tried to compile aircrack under Windows (using Linux Subsystem) and came across a line of code, that I believe has a typo in it.
linux.c:2077:
if (pl->fd_in && pl->fd_out && pl->fd_in == **pl_fd_out**) {

I fixed it by changing it to: 
if (pl->fd_in && pl->fd_out && pl->fd_in == **pl->fd_out**) {

**Comment by aircrack-ng** [comment]
Fixed in [r3046](https://trac.aircrack-ng.org/changeset/3046)
