### ISSUE TITLE
airodump-ng

### ISSUE THREAD

**Issue by lordkalki** [aircrack-ng/aircrack-ng-archive#18]
sometimes its run -1 like
 CH  1 ][ Elapsed: 28 s ][ 2014-10-30 20:52 ][ fixed channel mon0: -1          

 BSSID              PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH E

 2A:FB:D3:9A:DB:56  -30 100      274        7    0   1  54e  WPA2 CCMP   PSK  X

 BSSID              STATION            PWR   Rate    Lost    Frames  Probe     

 2A:FB:D3:9A:DB:56  80:56:F2:04:4F:7B    0    0e- 1e     0       10

**Comment by ZeroChaos-** [comment]
Please bother to read the wiki, this is a known issue caused by user error.

**Comment by lordkalki** [comment]
but where is your wiki ?

**Comment by ZeroChaos-** [comment]
if you cannot find www.aircrack-ng.org by yourself you might want to reconsider using aircrack-ng at all.

**Comment by lordkalki** [comment]
Actually i think that you have wiki in your github
