### ISSUE TITLE
The besside-ng-crawler is not being compiled

### ISSUE THREAD

**Issue by sethleedy** [aircrack-ng/aircrack-ng-archive#27]
I see in the Makefile for the src directory that it will be excluded if it is the Windows OS. However, I am attempting to create it on Ubuntu Linux. It will install the man page, but not the binary.

**Comment by aircrack-ng** [comment]
That's normal. You need libpcap for that and it isn't available for cygwin.

**Comment by sethleedy** [comment]
I am using gcc in Linux
