### ISSUE TITLE
wpaclean

### ISSUE THREAD

**Issue by markcoker** [aircrack-ng/aircrack-ng-archive#47]
when I'm cleaning a 3 captures i get the following error:

Assertion failed: (rc >= 0), function file_read, file file.c, line 126.
Abort trap: 6

if i do them separately it seems to work fine.

**Comment by aircrack-ng** [comment]
Could you upload the 3 captures somewhere?

**Comment by markcoker** [comment]
Very sorry recently removed them. (forgot i reported this late at night). 

This can be closed util further information can be found.
