### ISSUE TITLE
Huawei E5372 WiFi chipset

### ISSUE THREAD

**Issue by pensierinmusica** [aircrack-ng/aircrack-ng-archive#5]
Hi,

I'm trying to figure out what WiFi chipset does the [Huawei E5372](http://consumer.huawei.com/en/mobile-broadband/mobile-wifi/features/e5372-en.htm) mount.

Do you have any idea how one could figure it out?

Thanks!

**Comment by aircrack-ng** [comment]
Yes, follow the instructions in the wiki. There is a tutorial to help you determine it.

**Comment by pensierinmusica** [comment]
Hi @aircrack-ng, before posting this question I already tried all the methods described in the wiki, but couldn't figure the chipset out.

Here's a picture showing the label inside the product, in case it's useful:

![e5372](https://cloud.githubusercontent.com/assets/3594037/3215750/c69fcee0-efc4-11e3-83cb-294bc371e0a3.jpg)

Thanks for your help!  :)

**Comment by clopez** [comment]
This is not a chat.

Feel free to drop on the channel #aircrack-ng on Freenode, there someone maybe willing to help with your problem.

**Comment by pensierinmusica** [comment]
Ok, I just thought that figuring out complex cases could have been helpful to other people in solving similar situations in the future. Chat unfortunately doesn't leave any documentation behind. Thanks for the tip anyways  ;)

**Comment by pensierinmusica** [comment]
@clopez When I try to join the `aircrack-ng` room on Freenode I get this message: `You need to identify with network services to join the room "#aircrack-ng" on "irc.freenode.net".`

Where should I get the login credentials? Thanks  :)

**Comment by clopez** [comment]
You need to register your nick. Google for "freenode register"
