### ISSUE TITLE
Conn refused (pinger) in dcrack.py

### ISSUE THREAD

**Issue by ottojo** [aircrack-ng/aircrack-ng-archive#55]
Running "dcrack.py" just throws the error:

```
root@kali:~/Downloads# python dcrack.py 
Getting speed
('Speed', 1503)
('CID', 8573205185395703570L)
Conn refused (pinger)
Conn refused (pinger)
```

running as root (same errow when not root), internet connection works, system: Kali Linux, Python 2.7.9

**Comment by aircrack-ng** [comment]
There are a few missing parameters
