### ISSUE TITLE
make error: ‘rc4test_amd64_sse2’ undeclared

### ISSUE THREAD

**Issue by Horst4711** [aircrack-ng/aircrack-ng-archive#58]
Gentlemen,

i have an issue compiling the latest release on debian jessie. Anything i have missed?
Horst

---

gcc -g -W -Wall -O3  -msse2 -pthread -D_FILE_OFFSET_BITS=64 -D_REVISION=0  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -Iinclude   -c -o aircrack-ptw-lib.o aircrack-ptw-lib.c
aircrack-ptw-lib.c: In function ‘PTW_computeKey’:
aircrack-ptw-lib.c:592:20: error: ‘rc4test_amd64_sse2’ undeclared (first use in this function)
   state->rc4test = rc4test_amd64_sse2;
                    ^
aircrack-ptw-lib.c:592:20: note: each undeclared identifier is reported only once for each function it appears in
<builtin>: recipe for target 'aircrack-ptw-lib.o' failed
make[1]: **\* [aircrack-ptw-lib.o] Error 1

**Comment by aircrack-ng** [comment]
Should be fixed in r2832.
