### ISSUE TITLE
airodump-ng's realtime output is row size related?

### ISSUE THREAD

**Issue by Akagi201** [aircrack-ng/aircrack-ng-archive#6]
I add udp function to the dump_print() function is airodump-ng. I want to get the realtime result of the airodump-ng. So I need to run airodump-ng in background when startup. But I find that the airodump-ng is terminal windows size related. When the termial size(just row size) is smaller the the output, my server will not receive any udp datagram. What should I do to let airodump-ng run in background and not terminal size related.

**Comment by aircrack-ng** [comment]
Use screen.
