### ISSUE TITLE
airodump-ng Interfaces Windows

### ISSUE THREAD

**Issue by agieocean** [aircrack-ng/aircrack-ng-archive#61]
Using a awus036h adapter on windows 10 with the command
`airodump-ng --bssid xx:xx:xx:xx:xx:x "Wi-Fi 2"`
I am receiving the error
`Adapter <Wi-Fi 2> not supported`
However on aircrack's interface docs ([here](http://www.aircrack-ng.org/doku.php?id=compatibility_drivers)) it says 

> The Alfa AWUS036H is a very popular card with this chipset and it performs well the aircrack-ng suite.

What am I doing wrong?

**Comment by aircrack-ng** [comment]
It works well on Linux. On Windows, as explained on our website, you have to have a special driver that allows monitor mode and develop your own DLL (or find it online) to help airodump-ng interact with the driver itself.
