### ISSUE TITLE
1.2-rc4 not compile

### ISSUE THREAD

**Issue by earthGavinLee** [aircrack-ng/aircrack-ng-archive#65]
openwrt CC

In file included from linecount.cpp:62:0:
linecount.h:42:50: error: 'off_t' has not been declared
 EXTERNC unsigned int linecount(const char _file, off_t offset, size_t blksize);
                                                  ^
linecount.cpp:94:42: error: 'off_t' has not been declared
 unsigned int linecount(const char *file, off_t offset, size_t offsetmax) {
                                          ^
make[4]: *_\* [linecount.o] Error 1

**Comment by earthGavinLee** [comment]
#include <sys/types.h>

**Comment by earthGavinLee** [comment]
[aircrack-ng.zip](https://github.com/aircrack-ng/aircrack-ng/files/181475/aircrack-ng.zip)

**Comment by earthGavinLee** [comment]
ok
[aircrack-ng_v1.2-rc4.zip](https://github.com/aircrack-ng/aircrack-ng/files/181477/aircrack-ng_v1.2-rc4.zip)

**Comment by Mister-X-** [comment]
What architecture did you compile it for (CPU)? And what is the content of common.cfg?

**Comment by earthGavinLee** [comment]
thanks Mister-X
I have successfully compiled
aircrack-ng_v1.2-rc4.zip is makefile  and patch

The version of Openwrt is chaos_calmer r49007

**Comment by Mister-X-** [comment]
So, what was the issue? What CPU are you compiling it for.

**Comment by earthGavinLee** [comment]
My English is poor.
Now that the problem is solved. target system  is Oxford NAS782x/OX82x  Pogoplug V3 (ARM)

**Comment by Mister-X-** [comment]
I'm still interested to know what was the issue. Is it something on our side or your?
