### ISSUE TITLE
How to obtain the output of airodump?

### ISSUE THREAD

**Issue by libing64** [aircrack-ng/aircrack-ng-archive#71]
I want to use airodump-ng to do wifi localization in real time, but I don't know how to obtain all the APs' information (eg. mac address and rssi) in my program. 
Can anyone provide some help? Great thanks.

**Comment by ZeroChaos-** [comment]
this is a bug tracker, not a place to ask for help using the program

**Comment by libing64** [comment]
@ZeroChaos- 
I am sorry.
