### ISSUE TITLE
Add a switch to disable/lower the frequency of printf's

### ISSUE THREAD

**Issue by ijustlovemath** [aircrack-ng/aircrack-ng-archive#92]
printf's take a significant amount of time as compared to cracking operations, so it would be interesting to see if you would find any significant speedup if you only printed every 10,000th or 100,000th attempt, and none of the others.

**Comment by ijustlovemath** [comment]
I do see the -q option, but it would be nice if there were a way to simply lower the frequency of printf's and not simply lose them entirely.

**Comment by aircrack-ng** [comment]
Do you have numbers to show the difference?

**Comment by ijustlovemath** [comment]
Not for this particular program, but all I/O is slow as a general rule of thumb. At a minimum, setting stdout to be buffered would increase execution speed: http://stackoverflow.com/questions/1832489/printf-slows-down-my-program

And only printing the results for every N keys would be even less I/O to slow cracking down.

**Comment by aircrack-ng** [comment]
I'd say the difference is pretty insignificant and I'm gonna close the ticket.

Feel free to reopen it if you can come up with numbers (using time command for example).
